esphome:
  name: jc3248w535
  friendly_name: Guition 320x480 JC3248W535 Native

substitutions:
  home_page: energy
  log_level: DEBUG
  debug_sensor_logs: "true"

packages:
  common: !include common.yaml
  device: !include device.yaml
  layout: !include layouts/main.yaml
